#+TITLE: notes

* TODO
doom update --discard
investigate completion-styles variable?
<RET> in the profiler view does not call profiler-report-toggle-entry which is supposed to expand the entry - it always opens up the function
    -> its tab to expand, whoops
** general
use after!/localleader/:map for mappings
customise pretty-code-symbols-alist
projectile-switch-project-action ? may not be forced to select a file
* ivy
ivy-read example usage:
(ivy-read "Your choice:"
'("apple" "plum" "orange")
:action (lambda (choice)
(message "I chose %s" choice)))

pressing C-SPC while doing ivy search lets you preview
counsel-projectile-find-file-matcher might need to change this to match basename only?
pass params to rg: '--no-ignore -t cs -- <search terms>'

ctrl s to view history

honestly fuzzy isnt that great - disable fuzzy and just use a single space as a fuzzy match e.g. 'search cshtml' for fuzzy finding a file
also ivy-posframe seems to break with random bugs
I removed a bunch of commented out ivy config on 18/09/19 - see commit on that dayFin case I want to go back

From discord:
How do I do multi selections (i.e. marking candidates) in ivy?
Nevermind, figured it out: C-M-m to add current item to selection, C-M-n does the same, then automatically moves to the next line
* which key
explicit abort key
:desc "Which key abort" "ESC" #'which-key-abort
SPC h b = counsel-descbinds
* omnisharp
after finding usages, C-o will open in alternate window to <Enter> -> not true? just doesnt focus it.
enter always opens another window for me, really annoying...
omnisharp-solution-errors can be invoked with errors-only = true by going 'SPC u <M-x>' to use universal argument, this is due to (interactive "P")
apparently there is a way to use extra dlls e.g. roslynator, see omnisharp github
* evil
g- is used to decrement: (evil-numbers/dec-at-pt), g= to increment
gp to paste over highlighted section without overwriting clipboard
** surround
ysiw* to surround a word with *
ysaw* to do around the word (will include spaces next to it)
if you select with v/V then you can use S. Line selection seems bugged though, char goes to next line
cs"' to change " to '
ds" to delete surrounding "
highlight a region, press S f => you will get prompted for a function name to surround it with
* org
pressing S-TAB enough times will expand all headers
theres a way to control which level we expand headings to when we open a file by
changing the #+title part of the file, could try this out
ctrl-enter for a new bullet point
gh/gj/gk/gl for navigation
** calendar
ctrl + hjkl to move days when on calendar (C-c C-d)
* window manip
C-w m m to maximize/unmaximise a buffer
* elisp
macrostep collapse is bound to 'u', not 'c' as the info says
* searching
:pg TextToSearchFor to avoid the freezing that can occur when using the individual character search
SPC * to search for text under cursor
swiper is cool, SPC / b
ivy-rg - use -tlist --ivy to provide additional args - see counsel-rg definition
counsel-projectile-sort-files to make complete matches show above partial matches?
there was a github thread about this but i lost it
** deadgrep
i to enter insert mode. any change auto-saves file, unless file is open in a buffer, then it changes the file
* misc
As a side note, the functionality of avy-goto-char, avy-goto-char-2 and avy-goto-line are already available on the gsf, gss, and gsj/gsk keys, respectively. https://github.com/hlissner/doom-emacs/issues/1643
global-hl-line-mode to disable line highlighting + hl-line-mode
can then use 'SPC h F' / M-x describe-face to get the face at point to see why its coloured the way it is
https://lists.gnu.org/archive/html/emacs-devel/2008-02/msg00807.html
ivy-posframe needs to be LF line ending not CRLF, probably due to the 'Local
variables' section at the end...
use `doom update --discard` to ignore all the dirty worktree stuff
* new bindings i should use
alt + up/down to move lines via drag-stuff package
spc / j for ivy/jump-list
spc / / for swiper
spc c C / spc p C to rerun compliation
doom/help-search is cool
SPC h d {k,i,c} for config files
vc-region-history is cool
spc / {d,D} for RG under a directory (then C-c C-e for wgrep, then C-c C-c or ZZ to commit changes)
* Non-em
** windows
alt + esc cycles windows, same with alt+shift+esc
** git
https://stackoverflow.com/questions/40462111/git-prevent-commits-in-master-branch handy